name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.3
            gemfile: Gemfile
            redis-stack: latest
          - ruby: 2.7
            gemfile: gemfiles/redis.gemfile
            redis-stack: 6.2.6-v9
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis/redis-stack-server:${{ matrix.redis-stack }}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
